### ISSUE TITLE
Chrome Webstore

### ISSUE THREAD

**Issue by orschiro** [rishabhmw/sauron#1]
@rishabhmw are you planning on making your extension available on the Chrome Webstore? 😃👋

**Comment by rishabhmw** [comment]
@orschiro yes! It's actually pending review and it should be up any day now. You can still use the extension in developer mode on chrome. 

1.  Just clone/download the rep and put it in a folder
2.  Go to `chrome://extensions`
3.  Toggle the developer mode
4.  Click on 'Load unpacked' and select the folder.
5.  Your eyes love you again

**Comment by orschiro** [comment]
Oh great! 😃👋

Can you let me know here when it's published on the store?

-

**Comment by rishabhmw** [comment]
Yeah sure! I'll let you know and close this issue when the app gets published. Alternatively, I've added Store links/review status in the Readme.md for future visitors.

**Comment by orschiro** [comment]
😍🤗

-

**Comment by rishabhmw** [comment]
@orschiro Hi! Finally the extension got published. It will take a while before it gets indexed and shows up in search results. For now use this link: [Direct Link to Webstore](https://chrome.google.com/webstore/detail/sauron-dark-mode-for-all/fleolcdonmhbeppkijpfbhfhpceehiic)
).

**Comment by orschiro** [comment]
Thanks @rishabhmw! 😍🤗

I am testing it right now and will report back any suggestions I may have. 👍😄

**Comment by rishabhmw** [comment]
hi, @orschiro have you been using the extension lately? If yes, do you have any feedback?

**Comment by orschiro** [comment]
Hi Rishabh,

Yes, been using it and haven't found any issue thus far.

Thanks so much for Sauron! 🥳

-
