### ISSUE TITLE
File names in Google Drive turn unreadable after the page loads

### ISSUE THREAD

**Issue by quantumfrost** [rishabhmw/sauron#11]
If you wait for a few seconds after Google Drive loads, the file names turn black, making them unreadable.

![image](https://user-images.githubusercontent.com/4280297/55284678-6a246980-5349-11e9-87ca-dc6f7e599f84.png)

**Comment by rishabhmw** [comment]
Thanks for reporting the bug.

**Comment by rishabhmw** [comment]
The issue has been fixed as a consequence of fixing a bug where many websites such as Soundcloud were plagued by white elements. The Firefox update will be ready in a few hours and Chrome update will be released after it passes review from the chrome review team.
To get instant access to the update please clone this repository.
