### ISSUE TITLE
[Brave] Sauron doesn't seem to work on Reddit

### ISSUE THREAD

**Issue by reams** [rishabhmw/sauron#14]
I am using it with Brave, which is a Chromium browser. Here is an example -> https://www.reddit.com/r/windows/comments/4z2tep/are_there_seriously_just_12_extensions_for_edge/

**Comment by rishabhmw** [comment]
![It works fine on chrome.](https://user-images.githubusercontent.com/47751483/56404958-4fc61780-6287-11e9-8619-e3c5086b937a.PNG) Can you share a screenshot so I can test it out on Brave?

**Comment by rishabhmw** [comment]
@reams I am closing the issue since you haven't really described the issue in 2 days. You can open up a new issue with more details.
