### ISSUE TITLE
Unrecognized Manifest key

### ISSUE THREAD

**Issue by Chaython** [rishabhmw/sauron#15]
Applications is not recognized
```
    "applications":{
        "gecko":{
            "id": "saurondarkmode@rishabhmw.com"
        }

    }
```
Also when you scroll down google, or a site with a header anchored to the top of the screen it changes to white
![image](https://user-images.githubusercontent.com/6486343/60005258-5f693000-962b-11e9-9989-83355397407e.png)
![image](https://user-images.githubusercontent.com/6486343/60005281-6abc5b80-962b-11e9-8485-128cabf0e8bf.png)
also would be nice to have an easy color customizer, blue is straining

**Comment by rishabhmw** [comment]
This key is for Firefox users who wish to use the extension by directly cloning this repository. Firefox doesn't allow access to storage without a key.
This warning must be showing up in chrome however, it is inconsequential as the extension must work fine.
About color customization and header - they are planned for the next update so you should see them soon.
I will now close this issue. If you face any other problem feel free to open another issue.

**Comment by Chaython** [comment]
Firefox wouldn't load the clone
________________________________

**Comment by rishabhmw** [comment]
Are you following these instructions from the readme? Keep in mind that the zip must not have any folders in it.
1. Clone/Download the repository.
2. Chrome/Chromium based browser: More tools > Extensions > Turn on developer mode then Load unpacked > path to repository.
3. Firefox: Delete the screenshots folder and then zip all the files in sauron-master Go to Firefox and type about:debuging in address bar > Check enable add-on debugging then Load temporary add-on and then select the zip file you created.

**Comment by rishabhmw** [comment]
Also keep in mind that firefox will remove the extension on every browser restart as all addons installed from any other source other than the official store are loaded as temporary addons. Chrome however, keeps the extension as long as developer mode is enabled.
